### ISSUE TITLE
結果発表の順位がランキング順に表示されない問題点の改善

### ISSUE THREAD

**Issue by ARAN1218** [EaGitro/pp-SPOPPO-discordbot#9]
## 概要
結果発表の順位がランキング順に表示されない問題点を改善する

## 具体的取り組み
結果発表を表示する関数である `result` の処理を編集し、結果発表をゴールに近い順に表示させるようにする。
<img width="274" alt="スクリーンショット 2023-12-27 23 39 32" src="https://github.com/EaGitro/pp-SPOPPO-discordbot/assets/67265109/580ef7c6-6d94-48c3-ab97-553e7b68d10b">

## 参考資料
- [基本ソースコード](https://github.com/EaGitro/pp-SPOPPO-discordbot/tree/aran)

**Comment by EaGitro** [comment]
# 修正済

- 結果発表において、ピッタリランキングとドボンランキングが点数順に表示されるように修正
## 具体例

![img01](https://github.com/EaGitro/pp-SPOPPO-discordbot/assets/97268187/83ee90c9-c64a-4b98-b6dc-c77337883770)
![img02](https://github.com/EaGitro/pp-SPOPPO-discordbot/assets/97268187/637055d8-2891-4755-94fd-224c96514150)
![img03](https://github.com/EaGitro/pp-SPOPPO-discordbot/assets/97268187/e1c383ea-0325-4726-bbd4-2614303b3bbe)


## 備考
- コマンドが `commands/utility/` にあるが、修正を加えた関数 `result()` を** `commands/funcs/` の `result_func.js` に配置**
- それに伴い、`result()` 関数の実装を変更したため、** `result(interaction, target_scores, GOAL)` **というように呼び出す必要あり
- またその `result()` 関数を呼び出すための `import` を以下のように書く必要あり
    ```js
    const result_func = require("../funcs/result_func")
    const result = result_func.result_func;
    ```
- またファイル分けに伴い、  `commands/utility/pittari.js` の `result()` 関数の定義部を削除する必要あり
    - **コンフリクト防止のため未対応!!** (対応次第この issue を消すこと)

**Comment by ARAN1218** [comment]
未解決の問題として、ランキング形式で表示したいのに順位が記載されておらず、不親切な表示となってしまっている可能性がある。
この問題の解決には、例えば名前の横に1位、2位等順位の記載をすると良いかもしれない。

**Comment by EaGitro** [comment]
# 修正案2
- 結果発表において、ピッタリランキングとドボンランキングが点数順に表示されるように修正
- さらに順位とそれに応じたスタンプが表示されるように改善
  - ピッタリ: `:piedpiper:`
  - 1位: `:igyo:`
  - 3位まで: `:crown:`
  - ドボンワースト: `:__~1:`
  - それ以外のドボン: `:yosanoakiko:`

## 具体例

![修正案02-2](https://github.com/EaGitro/pp-SPOPPO-discordbot/assets/97268187/4c76ef65-eee1-493b-b962-738d7b9480fa)
![修正案02-1](https://github.com/EaGitro/pp-SPOPPO-discordbot/assets/97268187/17a10548-5ab9-4969-a53f-b17f6a1bcf5a)


## 備考

- ブランチは変わらず `ea-#9`
- `pittari.js` を修正
- コマンドが commands/utility/ にあるが、修正を加えた関数 result() を**commands/funcs/ の result_func.js に配置**    
    それに伴い、result() 関数の実装を変更したため、**result(interaction, target_scores, GOAL)**というように呼び出す必要あり
- import は修正済
- 元の定義部も修正済

**Comment by ARAN1218** [comment]
[Ea #9 修正案2: ランキング順に並べ、順位・スタンプを表示 #18](https://github.com/EaGitro/pp-SPOPPO-discordbot/pull/18)にてマージ済み
